好啊，来吧！总算知道怎么改了！
Teahouse-Studios/mcwzh-meme-web-builder pull request #212
Opened 2021-08-19 14:37 UTC by RxinnotRstar

https://github.com/Teahouse-Studios/mcwzh-meme-web-builder/issues/210

2021-08-19 14:39 UTC, zh9c418 commented
换个正常头像对你我都好（

2021-08-19 14:40 UTC, RxinnotRstar commented
> 
> 
> 换个正常头像对你我都好（

（半恼）

2021-08-19 14:43 UTC, XxLittleCxX requested changes

2021-08-19 14:43 UTC, XxLittleCxX commented on src/locales/zh-Meme.json
> +    "terms": "真得有人会看这些服务条款吗？",
这放在 footer 会不会显得太长了

2021-08-19 14:43 UTC, XxLittleCxX commented on src/locales/zh-Meme.json
> +    "disclaimer": "这些金主爸爸均未给 Teahouse Studios 梗体中文团队打钱，亦未强迫 Teahouse Studios 梗体中文团队将其添加至金主爸爸列表——这只是 Teahouse Studios 梗体中文团队对他们表示“这个可以有！“最诚挚的感谢。❤️"
引号是不是反了

2021-08-19 14:43 UTC, XxLittleCxX commented on src/locales/zh-Meme.json
> +        "3": "使用正式的普通话，不要用梗体中文或者其它语言提交。",
强调其他语言感觉没必要

2021-08-19 14:43 UTC, XxLittleCxX commented on src/locales/zh-Meme.json
> +    "梗体中文是一个持续更新的项目，欢迎 常 回 家 看 看 。"
这个空格有啥意义吗（

2021-08-19 14:43 UTC, XxLittleCxX commented on src/locales/zh-Meme.json
> +      "label": "游戏版本（不是版本，是版本）"
没看懂意义

2021-08-19 15:03 UTC, RxinnotRstar commented on src/locales/zh-Meme.json
> +    "梗体中文是一个持续更新的项目，欢迎 常 回 家 看 看 。"
与“常”前面的空格照应

2021-08-19 15:04 UTC, RxinnotRstar commented on src/locales/zh-Meme.json
> +      "label": "游戏版本（不是版本，是版本）"
我也忘了我为什么要写这个……删了

2021-08-19 15:05 UTC, Dianliang233 commented on src/locales/zh-Meme.json
> +    "梗体中文是一个持续更新的项目，欢迎 常 回 家 看 看 。"
不需要

2021-08-19 15:05 UTC, RxinnotRstar commented on src/locales/zh-Meme.json
> +    "terms": "真得有人会看这些服务条款吗？",
个人认为不会。（原文也长啊）

2021-08-19 15:07 UTC, XxLittleCxX commented on src/locales/zh-Meme.json
> +    "terms": "真得有人会看这些服务条款吗？",
![image](https://user-images.githubusercontent.com/26459759/130093163-74829b2f-e5d1-4ba2-866a-1922cd2964cd.png)

![image](https://user-images.githubusercontent.com/26459759/130093200-5f30bab3-fdec-471a-97a5-d9c76df24d71.png)

倒还行其实

@Dianliang233

2021-08-19 15:07 UTC, Dianliang233 commented on src/locales/zh-Meme.json
> +    "terms": "真得有人会看这些服务条款吗？",
这么长会换行的

2021-08-19 15:17 UTC, Dianliang233 commented on src/locales/zh-Meme.json
> -    }
为什么删了？

2021-08-19 15:17 UTC, Dianliang233 commented on src/locales/zh-Meme.json
> +      "subtitle": "SPGoding 是一位 Bugjang 管理员、泥潭噫术家，代表作《大憨批》VSCode 插件。ta 让梗体中文白嫖了 7 天泥潭广告位，背后的原因让人暖心。",
这里没必要二次梗化

2021-08-19 15:17 UTC, Dianliang233 commented on src/locales/zh-Meme.json
> +      "sure": "如果您确信梗体中文有问题，您便可以向我们汇报。如果您有一个建议，这个可以有！",
语病

2021-08-19 15:17 UTC, Dianliang233 commented on src/locales/zh-Meme.json
> +        "2": "确保您不会变成复读机，提交的问题没有被他人提交过。",
优化成
> 确保您不会变成他人提交过的问题的复读机

2021-08-19 15:17 UTC, Dianliang233 commented on src/locales/zh-Meme.json
> +    "title": "梗体中文 · 云 服 务",
不妥

2021-08-19 15:17 UTC, Dianliang233 commented on src/locales/zh-Meme.json
> +    "terms": "真得有人会看这些服务条款吗？",
> 得
typo

没必要二次梗化

2021-08-19 15:18 UTC, XxLittleCxX commented on src/locales/zh-Meme.json
> -    }
是不是你拉了 upstream, 然后这个文件没更新

2021-08-19 15:19 UTC, Dianliang233 commented on src/locales/zh-Meme.json
> -    }
我 merge 过，应该是他无视冲突直接删掉incoming changes然后就提交了

2021-08-19 15:22 UTC, RxinnotRstar commented on src/locales/zh-Meme.json
> -    }
哦那个时候网络卡顿了一下

2021-08-19 15:27 UTC, RxinnotRstar commented on src/locales/zh-Meme.json
> -    }
为什么我每次都会删掉些奇奇怪怪的东西（恼）

2021-08-19 15:27 UTC, RxinnotRstar commented on src/locales/zh-Meme.json
> +      "subtitle": "SPGoding 是一位 Bugjang 管理员、泥潭噫术家，代表作《大憨批》VSCode 插件。ta 让梗体中文白嫖了 7 天泥潭广告位，背后的原因让人暖心。",
为何？

2021-08-19 15:30 UTC, RxinnotRstar commented on src/locales/zh-Meme.json
> +        "2": "确保您不会变成复读机，提交的问题没有被他人提交过。",
确保您不会变成复读机，请检查您提交的问题没有被他人提交过。

如何？

2021-08-19 15:31 UTC, RxinnotRstar commented on src/locales/zh-Meme.json
> +    "title": "梗体中文 · 云 服 务",
在线生草

如何？

2021-08-19 15:32 UTC, Dianliang233 commented on src/locales/zh-Meme.json
> +        "2": "确保您不会变成复读机，提交的问题没有被他人提交过。",
> 确保您不会变成复读机，请检查您提交的问题没有被他人提交过。

一股西化中文味

2021-08-19 15:32 UTC, RxinnotRstar commented on src/locales/zh-Meme.json
> +    "terms": "真得有人会看这些服务条款吗？",
footer 长一点看着气派（

2021-08-19 15:33 UTC, RxinnotRstar commented on src/locales/zh-Meme.json
> +    "terms": "真得有人会看这些服务条款吗？",
“真得有人会看这些×××吗？”来自原版MC（原 声 大 碟）

2021-08-20 03:27 UTC, RxinnotRstar commented
Check一下吧

2021-08-23 09:34 UTC, Dianliang233 commented on src/locales/zh-Meme.json
> +    "title": "梗体中文 · 云 服 务",
> 在线生草

还行

2021-08-23 09:35 UTC, Dianliang233 commented
你让我review，可是我已经review过了

2021-08-23 13:59 UTC, RxinnotRstar commented
“真得有人会看这些……吗？”来自Minecraft原版简体中文，本处为致敬该tip。

2022-06-01 13:37 UTC, closed without merging